const category = [
    "Aksesoris", "Air Terjun", "Akar", "Akuarium", "Alam", "Alat Musik", "Aliran Air", 
    "Anggur", "Angin", "Anime", "Anime Cewe", "Anime Cowo", "Apel", "Aqua", "Arsitektur", 
    "Aula", "Awan", "Ayam", "Ayunan", "Badai", "Bagan", "Bajak Laut", "Bambu", 
    "Bandara", "Bangkai Kapal", "Bangunan", "Banjir", "Barisan Pegunungan", 
    "Batu", "Bayangan", "Bayam", "Belanja", "Benteng", "Berkemah", "Berlian", 
    "Berselancar", "Beruang", "Besar", "Binatang Buas", "Binatang Peliharaan", 
    "Biota Laut", "Biru", "Bola", "Bonsai", "Borobudur", "Bulan", "Bulutangkis", 
    "Bunga", "Bunga Matahari", "Burung", "Burung Hantu", "Cahaya", "Candi", 
    "Candi Kuno", "Cangkir", "Cerah", "Cermin", "Cinta", "Close-up", "Coklat", 
    "Danau", "Dataran Tinggi", "Daun", "Debu", "Dedauan", "Dedaunan", "Dekorasi", 
    "Demam", "Desa", "Detektif", "Dinding", "Disco", "Dokter", "Domba", "Dunia", 
    "Duri", "Dusun", "Duyung", "Embun", "Emas", "Eksplorasi", "Es", "Es Batu", 
    "Es Krim", "Fantasi", "Feri", "Film", "Flora", "Foto Lama", "Fotografi Malam", 
    "Fotografi Udara", "Gadget", "Gajah", "Gambar", "Gedung", "Gedung Pencakar Langit", 
    "Gelombang", "Gelanggang", "Gerhana", "Gerimis", "Gerobak", "Gerombolan", 
    "Gitar", "Globe", "Gunung", "Gunung Api", "Gurun", "Halaman", "Hantu", 
    "Harmoni", "Hati", "Hewan", "Hiasan", "Hobi", "Hujan", "Hutan", "Hutan Pinus", 
    "Hutan Tropis", "Ilalang", "Ilusi", "Imlek", "Injak", "Istana", "Jalan", 
    "Jalan Setapak", "Jalan Tol", "Jalanan Kota", "Jambatan", "Jambu", "Janji", 
    "Jarak", "Jaring", "Jari", "Jasa", "Jejak", "Jembatan", "Jendela", "Jeruk", 
    "Jimat", "Jingga", "Jubah", "Jungkat-Jungkit", "Kabut", "Kaca", "Kacang", 
    "Kaki", "Kaktus", "Kaktus", "Kalung", "Kamera", "Kampung", "Kapal", 
    "Kapal Layar", "Kapal Selam", "Karang", "Karet", "Karnaval", "Kawasan", 
    "Kayu", "Kebahagiaan", "Kebersihan", "Kebun", "Kebun Binatang", "Kebun Raya", 
    "Keindahan", "Kejutan", "Kekasih", "Kelapa", "Kelinci", "Keluarga", "Kemah", 
    "Kemarahan", "Kembang Api", "Kendaraan", "Kerajaan", "Keramik", "Kereta", 
    "Kereta Api", "Keseimbangan", "Kesederhanaan", "Keseharian", "Kesepian", 
    "Kesetiaan", "Kesehatan", "Ketenangan", "Ketepatan", "Kincir Angin", "Kios", 
    "Kisah", "Klasik", "Klinik", "Koin", "Kolam", "Kolam Renang", "Kompas", 
    "Kongres", "Konser", "Kota", "Kota Mati", "Kucing", "Kuliner", "Kupu-kupu", 
    "Ladang", "Lampu", "Langit", "Lapangan", "Laut", "Lava", "Layang-Layang", 
    "Lemari", "Lembah", "Lensa", "Liburan", "Lingkaran", "Lintasan", "Lukisan", 
    "Lumbung", "Mabuk", "Magnet", "Mahar", "Maid", "Makanan", "Makro", "Mangga", 
    "Mangrove", "Manusia", "Marmer", "Matahari Terbit", "Matahari Terbenam", 
    "Melamun", "Menari", "Menyelam", "Menara", "Mentari", "Mercusuar", "Mie", 
    "Mobil", "Mobil Balap", "Mobil Kuno", "Monas", "Monumen", "Monyet", "Museum", 
    "Musik", "Musim Dingin", "Musim Gugur", "Musim Hujan", "Musim Kemarau", 
    "Musim Panas", "Musim Semi", "Padang Pasir", "Padang Rumput", "Padi", 
    "Pahlawan", "Palem", "Panda", "Pantai", "Papan", "Papan Nama", "Papan Selancar", 
    "Pasar", "Pasir", "Paus", "Paus Pembunuh", "Pedagang", "Pedestrian", "Pelangi", 
    "Pelaut", "Pelindung", "Pemandangan", "Pemandangan Udara", "Pematang", 
    "Pendekar", "Pengadilan", "Penyelam", "Penyelamatan", "Perahu", "Perbukitan", 
    "Perdagangan", "Perjalanan", "Perkampungan", "Permadani", "Pernikahan", 
    "Peta", "Petualangan", "Piano", "Pijat", "Piramida", "Piring", "Planet", 
    "Plaza", "Pohon", "Pohon Apel", "Pohon Kelapa", "Polisi", "Prajurit", 
    "Praja", "Pramugari", "Prasasti", "Presiden", "Pulau", "Puncak", "Pusat Kota", 
    "Putih", "Rakyat", "Rantai", "Rawa", "Rencana", "Rerumputan", "Rindu", 
    "Roda", "Roket", "Rumah", "Rumah Adat", "Rumah Makan", "Rumah Sakit", 
    "Rusa", "Sabun", "Sagu", "Sajadah", "Sakit", "Sakura", "Sampan", "Sapi", 
    "Sari", "Sawah", "Savana", "Sayuran", "Sebuah", "Sedikit", "Selancar", 
    "Sembahyang", "Semut", "Seni", "Senja", "Senyum", "Sepatu", "Sepeda", 
    "Sepeda Motor", "Serangga", "Siluet", "Sketsa", "Sosial", "Spa", "Sungai", 
    "Surat", "Taman", "Taman Bermain", "Taman Nasional", "Taman Safari", 
    "Taman Wisata", "Tebing", "Teknologi", "Tenda", "Tepi Danau", "Tepi Laut", 
    "Teratai", "Teras Sawah", "Terminal", "Tidur", "Toko", "Topeng", "Tradisional", 
    "Transportasi", "Tugu", "Udara", "Ular", "Universitas", "Unta", "Vulkanik", 
    "Wajah", "Waktu", "Warna", "Warung", "Wayang", "Wisata", "Wol", "Yayasan", 
    "Zebra", "Ziarah"
];


export default category